apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "khub.fullname" . }}
  labels:
    app.kubernetes.io/name: khub
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  KHUB_DB: {{ .Values.config.db | quote }}
  KHUB_LIBRARY: {{ .Values.config.library | quote }}
